# Generated by Django 5.0.2 on 2024-02-28 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0002_alter_budget_budget_type_alter_budget_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='descriptions',
            new_name='description',
        ),
    ]
